### ISSUE TITLE
No operation saved

### ISSUE THREAD

**Issue by dtraore** [DamienHarper/auditor-bundle#133]
Hello! I just install the bundle,

I'm on symfony 4.2

this is my configuration file:

```
dh_doctrine_audit:
    table_prefix: 'audit_'
    table_suffix: ''
    timezone: 'Europe/Paris'
    enabled: true
    entities:
        AppCore\Entity\MyEntity: ~
```

the schema update commande work fine
`bin/console doctrine:schema:update --force`

But when I update or create content (CRUD operation), There are no change in /audit, to debug I did dump in the onFlush()

this is where I did dump 

```
public function onFlush(OnFlushEventArgs $args): void
    {
        $em = $args->getEntityManager();
        $transaction = new AuditTransaction($this->manager->getHelper());

        dump($em, $transaction->getEntityManager(), __METHOD__);
```

Here the results of dump 

![image](https://user-images.githubusercontent.com/7816604/69902153-62124300-138a-11ea-8003-2c42a06b201d.png)

![image](https://user-images.githubusercontent.com/7816604/69902160-82da9880-138a-11ea-8297-c1c09df6119f.png)

Two unitOfWork are different.

To fix this temporary I did this in the DoctrineSubscriber : $transaction->setEntityManager($em);
And add setEntityManager method to AuditTransaction
Thanks in advance.

**Comment by DamienHarper** [comment]
Not only UnitOfWork are different but EntityManager too... that's usually the case when using a secondary database to store audits. 
Could you please provide me a sample test project or code sample to reproduce the issue?

**Comment by dtraore** [comment]
This is my doctrine configuration file content:

```
doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            DonisoCore:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Doniso/Core/Entity'
                prefix: 'DonisoCore\Entity'
                alias: DonisoCore
            DonisoUsers:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Doniso/Users/Entity'
                prefix: 'DonisoUsers\Entity'
                alias: DonisoUsers
```
Sorry I don't it is difficult to provide sample test but I can share all configurations files which can help

**Comment by DamienHarper** [comment]
What's the namespace of your entities? (the ones you want to audit)

**Comment by dtraore** [comment]
This is a sample of one ENtity 

```
namespace DonisoCore\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="DonisoCore\Repository\CourseRepository")
 */
class Course extends BaseEntity
{
}
```

in my database I have a table called course_audit

And in the Audit route /audit

I have My Entity there DonisoCore\Entity\Course

**Comment by DamienHarper** [comment]
Your `dh_doctrine_audit.yaml` file mentions `AppCore\Entity\MyEntity` as an audited entity (so under the `AppCore\Entity` namespace) but your `doctrine.yaml` suggests your entities are in `DonisoCore\Entity` and `DonisoUsers\Entity` namespaces.

Are you using version 3.x of the bundle?

**Comment by DamienHarper** [comment]
Oh you replied before I post my last message :) so I suppose you use 3.X version of the bundle and  annotations to declare which entity is auditable

**Comment by dtraore** [comment]
this is the real content of my dh config file 

```
dh_doctrine_audit:
    table_prefix: 'audit_'
    table_suffix: ''
    timezone: 'Europe/Paris'
    enabled: true
    entities:
        DonisoCore\Entity\Academy: null
        DonisoCore\Entity\CAP: null
        DonisoCore\Entity\Course: null
```

**Comment by dtraore** [comment]
I'm using 3.0.0 based on composer show command

**Comment by DamienHarper** [comment]
@dtraore thanks, now I need some time to try to reproduce the issue on my side. I'll keep you updated.

**Comment by dtraore** [comment]
Ok thanks to you.

**Comment by DamienHarper** [comment]
@dtraore could you post the result of `bin/console debug:config DoctrineBundle` please?
Also, a sample of code that reproduce the issue would be helpful.

**Comment by NicoCoulon** [comment]
Had the same issue and implemented the same workaround described in post 1.

I'm using version 3.2.3.

Here is my output of `bin/console debug:config DoctrineBundle` :
```
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                dbname: mylabdata
                host: localhost
                port: 5432
                user: mylabdata_user
                password: mylabdata_password
                driver: pdo_pgsql
                memory: true
                charset: UTF8
                server_version: '10.9'
                logging: true
                profiling: true
                profiling_collect_backtrace: false
                options: {  }
                mapping_types: {  }
                default_table_options: {  }
                slaves: {  }
                shards: {  }
        types: {  }
    orm:
        auto_generate_proxy_classes: true
        default_entity_manager: default
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: /home/osboxes/_dev/Tim_Backend_API_PHP/src/Entity
                        prefix: App\Entity
                        alias: App
                        mapping: true
                query_cache_driver:
                    type: array
                    namespace: null
                    cache_provider: null
                metadata_cache_driver:
                    type: array
                    namespace: null
                    cache_provider: null
                result_cache_driver:
                    type: array
                    namespace: null
                    cache_provider: null
                class_metadata_factory_name: Doctrine\ORM\Mapping\ClassMetadataFactory
                default_repository_class: Doctrine\ORM\EntityRepository
                quote_strategy: doctrine.orm.quote_strategy.default
                entity_listener_resolver: null
                repository_factory: doctrine.orm.container_repository_factory
                hydrators: {  }
                filters: {  }
        proxy_dir: '%kernel.cache_dir%/doctrine/orm/Proxies'
        proxy_namespace: Proxies
        resolve_target_entities: {  }
```

Please let me know if you need something else.

Btw, thanks for this nice package

**Comment by dtraore** [comment]
sorry @DamienHarper I was off last weeks.
I will be back with the command output

**Comment by DamienHarper** [comment]
Probably related to #157

**Comment by dtraore** [comment]
Hello here you is the output of doctrine bundle config command:


```
λ php bin/console debug:config DoctrineBundle

Current configuration for "DoctrineBundle"
==========================================

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: pdo_mysql
                server_version: '5.7'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
                url: '%env(resolve:DATABASE_URL)%'
                host: localhost
                port: null
                user: root
                password: null
                logging: true
                profiling: true
                profiling_collect_backtrace: false
                options: {  }
                mapping_types: {  }
                slaves: {  }
                shards: {  }
        types: {  }
    orm:
        auto_generate_proxy_classes: true
        default_entity_manager: default
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                mappings:
                    DonisoCore:
                        is_bundle: false
                        type: annotation
                        dir: 'D:\wamp64\www\doniso/src/Doniso/Core/Entity'
                        prefix: DonisoCore\Entity
                        alias: DonisoCore
                        mapping: true
                    DonisoUsers:
                        is_bundle: false
                        type: annotation
                        dir: 'D:\wamp64\www\doniso/src/Doniso/Users/Entity'
                        prefix: DonisoUsers\Entity
                        alias: DonisoUsers
                        mapping: true
                query_cache_driver:
                    type: array
                    namespace: null
                    cache_provider: null
                metadata_cache_driver:
                    type: array
                    namespace: null
                    cache_provider: null
                result_cache_driver:
                    type: array
                    namespace: null
                    cache_provider: null
                class_metadata_factory_name: Doctrine\ORM\Mapping\ClassMetadataFactory
                default_repository_class: Doctrine\ORM\EntityRepository
                quote_strategy: doctrine.orm.quote_strategy.default
                entity_listener_resolver: null
                repository_factory: doctrine.orm.container_repository_factory
                hydrators: {  }
                filters: {  }
        proxy_dir: '%kernel.cache_dir%/doctrine/orm/Proxies'
        proxy_namespace: Proxies
        resolve_target_entities: {  }
```

The hot fix that I did is to override some file which are : 

  ```
dh_doctrine_audit.event_subscriber.doctrine:
      class: DonisoAdmin\AuditHotFix\DoctrineSubscriber
      arguments: ["@dh_doctrine_audit.manager"]
      tags:
        - { name: doctrine.event_subscriber, connection: default }

    dh_doctrine_audit.manager:
      class: DonisoAdmin\AuditHotFix\AuditManager
      arguments:
        - "@dh_doctrine_audit.configuration"
        - "@dh_doctrine_audit.helper"
      public: true

    DonisoAdmin\AuditHotFix\AuditManager:
      alias: dh_doctrine_audit.manager
      public: true
    DonisoCore\Security\ClassRoomVoter:
      class: DonisoCore\Security\ClassRoomVoter
      tags: [ security.voter ]
```

I can share these file if need.

**Comment by DamienHarper** [comment]
@dtraore Sorry for the delay, this should be fixed in `master` branch as you can now configure several entity managers both for storage and as audit event sources. I close this issue but feel free to reopen it if needed.

**Comment by e9li** [comment]
Hello, I just updated from the 'old' audit which was working perfectly with Symfony 5.2. The configuration is default and really standard with one DB. With the old everything word fine but now nothing gets logged.  Someone has an idea what could be wrong?


```
Current configuration for "DoctrineBundle"
==========================================

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                driver: pdo_mysql
                server_version: '5.7'
                charset: utf8mb4
                default_table_options:
                    collate: utf8mb4_unicode_ci
                host: localhost
                port: null
                user: root
                password: null
                logging: true
                profiling: true
                profiling_collect_backtrace: false
                profiling_collect_schema_errors: true
                options: {  }
                mapping_types: {  }
                slaves: {  }
                replicas: {  }
                shards: {  }
        types: {  }
    orm:
        auto_generate_proxy_classes: true
        default_entity_manager: default
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: /Users/rafaelegli/Desktop/Server/drehscheibe/src/Entity
                        prefix: App\Entity
                        alias: App
                        mapping: true
                query_cache_driver:
                    type: null
                metadata_cache_driver:
                    type: null
                result_cache_driver:
                    type: null
                class_metadata_factory_name: Doctrine\ORM\Mapping\ClassMetadataFactory
                default_repository_class: Doctrine\ORM\EntityRepository
                quote_strategy: doctrine.orm.quote_strategy.default
                entity_listener_resolver: null
                repository_factory: doctrine.orm.container_repository_factory
                hydrators: {  }
                filters: {  }
        proxy_dir: '%kernel.cache_dir%/doctrine/orm/Proxies'
        proxy_namespace: Proxies
        resolve_target_entities: {  }
```

```
dh_auditor:
    enabled: true
    timezone: 'Europe/Zurich'
    providers:
        doctrine:
            table_prefix: ~
            table_suffix: '_audit'
            entities:
                App\Entity\Action: ~
                App\Entity\ActionUser: ~
                App\Entity\Address: ~
                App\Entity\AddressContactNote: ~
                App\Entity\AddressLog: ~
                App\Entity\Alert: ~
```
