### ISSUE TITLE
Configuration for several doctrine connection/em

### ISSUE THREAD

**Issue by gam6itko** [DamienHarper/auditor-bundle#157]
I have project which has several connections and em's. 

My doctrine config looks like this
```yaml
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                # ...
            foo:
                # ...
            bar:
                # ...

    orm:
        entity_managers:
            default:
                connection: default
            foo:
                connection: foo
            bar:
                connection: bar
```

Now I need to track changes for Entities which managed by `foo` em.
Looks like your bundle works only with `default` connection. It will be very useful to allow user to configure audits for entities in different em's
