### ISSUE TITLE
Configuration vs. Annotation

### ISSUE THREAD

**Issue by colonelclick** [DamienHarper/auditor-bundle#196]
I was trying to use configuration and I received no errors but it did not work*, so I had to switch to annotation.

*I added entries to dh_doctrine_audit.yaml (below) but there was no diff detected for a doctrine migration, and the entities were not logged by my application, but no errors were generated.

However, as soon as I added the annotation for `* @Audit\Auditable` into the Customer entity shown in the yaml below a diff was able to be generated and the entity was correctly logged.

Is this expected? Or should it work based purely on configuration?

```
dh_doctrine_audit:
    ignored_columns:
        - createdAt
        - updatedAt
    entities:
        App/Entity/Customer: ~
```
