### ISSUE TITLE
No route found for "GET /audit"

### ISSUE THREAD

**Issue by lcpaf** [DamienHarper/auditor-bundle#223]
I'm probably missing some very important detail, but I'm not able to get `/audit` view to work.
Everything is work nicely, all the audit tables are created and populated, however, the route seems to be off.

This is my configuration:

```yaml
dh_doctrine_audit:
    timezone: 'Europe/Berlin'
    enabled: true
    enabled_viewer: true
    table_prefix: '_audit_'
    table_suffix: ''
    entities:
        App\Entity\Contact: ~
        App\Entity\BankAccount: ~
```

And this is my environment:

* Symfony 5.1.8
* PHP 7.4.12
