### ISSUE TITLE
Change viewer's URL

### ISSUE THREAD

**Issue by jean-gui** [DamienHarper/auditor-bundle#226]
| Q                           | A
| ----------------------------| -----------------------
| `auditor-bundle` version    | 4.0.3
| PHP version                 | 7.4.3
| Database                    | MySQL

#### Summary

It used to be possible to customize the URL at which the viewer was available  by adding the following code to config/routes.yaml:
```yaml
dh_doctrine_audit:
    resource: "@DHDoctrineAuditBundle/Controller/"
    type: annotation
    prefix: /admin/
```
That doesn't seem to be possible anymore.

#### Current behavior

I get the following error:

> Do not add the "audit" loader twice in @DHAuditorBundle/Controller/ (which is being imported from "/media/perso/PhpstormProjects/main/config/routes.yaml"). Make sure the "DHAuditorBundle" bundle is correctly registered and loaded in the application kernel class. If the bundle is registered, make sure the bundle path "@DHAuditorBundle/Controller/" is not empty.

#### How to reproduce

I've attempted what's described at https://damienharper.github.io/auditor-docs/docs/auditor-bundle/configuration/general.html#enablingdisabling-audit-viewer :
```yaml
dh_auditor:
    providers:
        doctrine:
            viewer: false
```
```yaml
dh_auditor:
    resource: "@DHAuditorBundle/Controller/"
    type: auditor
    prefix: /admin/
```
I've also tried without setting dh_auditor.providers.doctrine.viewer to false, the same thing happens.

#### Expected behavior

With the config shown above, audit viewer should be available at /admin/audit.

Thanks
