### ISSUE TITLE
Not saving operations

### ISSUE THREAD

**Issue by e9li** [DamienHarper/auditor-bundle#228]
Hello, I just updated from the 'old' audit which was working perfectly with Symfony 5.2. The configuration is default and really standard with one DB. With the old everything worked fine but now nothing gets logged. Someone has an idea what could be wrong?

Symfony 5.2.1
damienharper/auditor: *
damienharper/auditor-bundle: *
doctrine/annotations: *

```
Current configuration for "DoctrineBundle"
==========================================

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                driver: pdo_mysql
                server_version: '5.7'
                charset: utf8mb4
                default_table_options:
                    collate: utf8mb4_unicode_ci
                host: localhost
                port: null
                user: root
                password: null
                logging: true
                profiling: true
                profiling_collect_backtrace: false
                profiling_collect_schema_errors: true
                options: {  }
                mapping_types: {  }
                slaves: {  }
                replicas: {  }
                shards: {  }
        types: {  }
    orm:
        auto_generate_proxy_classes: true
        default_entity_manager: default
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: xyz/src/Entity
                        prefix: App\Entity
                        alias: App
                        mapping: true
                query_cache_driver:
                    type: null
                metadata_cache_driver:
                    type: null
                result_cache_driver:
                    type: null
                class_metadata_factory_name: Doctrine\ORM\Mapping\ClassMetadataFactory
                default_repository_class: Doctrine\ORM\EntityRepository
                quote_strategy: doctrine.orm.quote_strategy.default
                entity_listener_resolver: null
                repository_factory: doctrine.orm.container_repository_factory
                hydrators: {  }
                filters: {  }
        proxy_dir: '%kernel.cache_dir%/doctrine/orm/Proxies'
        proxy_namespace: Proxies
        resolve_target_entities: {  }
```

```
dh_auditor:
    enabled: true
    timezone: 'Europe/Zurich'
    providers:
        doctrine:
            table_prefix: ~
            table_suffix: '_audit'
            entities:
                App\Entity\Action: ~
                App\Entity\ActionUser: ~
                App\Entity\Address: ~
                App\Entity\AddressContactNote: ~
                App\Entity\AddressLog: ~
                App\Entity\Alert: ~
```

_Originally posted by @e9li in https://github.com/DamienHarper/auditor-bundle/issues/133#issuecomment-751665031_

**Comment by e9li** [comment]
At the moment I do not use annotations for audits. But I tried annotations in an entity but that's also not logging anything.

**Comment by N4IR0** [comment]
I have almost the same problem, only with the difference that it works for me in the development environment, but as soon as I change the environment to prod it does not work anymore. The audit viewer is working and table schema is up to date. 

Installed packages:
```
Symfony: ^5.2
damienharper/auditor-bundle: ^4
```

Doctrine configuration:
```
Current configuration for "DoctrineBundle"
==========================================

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: pdo_pgsql
                host: postgres
                port: null
                dbname: symfony
                user: symfony
                password: dev
                charset: UTF8
                logging: false
                profiling: false
                profiling_collect_backtrace: false
                profiling_collect_schema_errors: true
                options: {  }
                mapping_types: {  }
                default_table_options: {  }
                slaves: {  }
                replicas: {  }
                shards: {  }
        types: {  }
    orm:
        auto_generate_proxy_classes: false
        default_entity_manager: default
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: /code/src/Entity
                        prefix: App\Entity
                        alias: App
                        mapping: true
                metadata_cache_driver:
                    type: service
                    id: doctrine.system_cache_provider
                query_cache_driver:
                    type: service
                    id: doctrine.system_cache_provider
                result_cache_driver:
                    type: service
                    id: doctrine.result_cache_provider
                class_metadata_factory_name: Doctrine\ORM\Mapping\ClassMetadataFactory
                default_repository_class: Doctrine\ORM\EntityRepository
                quote_strategy: doctrine.orm.quote_strategy.default
                entity_listener_resolver: null
                repository_factory: doctrine.orm.container_repository_factory
                hydrators: {  }
                filters: {  }
        proxy_dir: '%kernel.cache_dir%/doctrine/orm/Proxies'
        proxy_namespace: Proxies
        resolve_target_entities: {  }
```

dh_auditor.yaml:
```
dh_auditor:
    enabled: true
    timezone: 'Europe/Berlin'
    providers:
        doctrine:
            table_prefix: ~
            table_suffix: '_audit'
            ignored_columns:
                - id
                - createdAt
                - updatedAt
            entities:
                App\Entity\Instance: ~
                App\Entity\Server: ~
                App\Entity\Task:
                    ignored_columns:
                        - callback
                        - payload
                        - returnPayload
                        - taskQueue
                        - startedAt
                        - finishedAt
```
