### ISSUE TITLE
No logging with easyadmin3

### ISSUE THREAD

**Issue by Upgreydd** [DamienHarper/auditor-bundle#235]
Hey! I've configured auditor like this:
```
dh_auditor:
    enabled: true
    timezone: 'UTC'
    providers:
        doctrine:
            table_prefix: null
            table_suffix: '_audit'
            viewer: true
            entities:
                App\Entity\File: ~
                App\Entity\User: ~
                App\Entity\NavUnit: ~
            ignored_columns:
                - createdAt
                - updatedAt
```
but nothing is logged. I've tried to debug it and I'm not sure why it's not working.
