### ISSUE TITLE
How to store audit tables in other database ?

### ISSUE THREAD

**Issue by chrisbiaz** [DamienHarper/auditor-bundle#243]
| Q                           | A
| ----------------------------| -----------------------
| `auditor-bundle` version    | 4.0.4
| PHP version                 | 7.4.12
| Database                    | PostgreSQL

Hello,
I try to save my audit tables with another manager.
I configure the bundle with this code :

<pre>
doctrine:
    dbal:
        default_connection: default
        connections:
            default: &connection
                driver: 'pdo_pgsql'
                charset: UTF8
                server_version: '%env(POSTGRES_VERSION)%'
                host: '%env(POSTGRES_HOST)%'
                port: '%env(POSTGRES_PORT)%'
                dbname: '%env(POSTGRES_DB)%'
                user: '%env(POSTGRES_USER)%'
                password: '%env(POSTGRES_PASSWORD)%'
            log:
                <<: *connection
                dbname: '%env(POSTGRES_DB)%-log'
    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: '%kernel.debug%'
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
            log:
                connection: log
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
</pre>

<pre>
dh_auditor:
    enabled: true
    timezone: 'Europe/Paris'
    user_provider: ~
    providers:
        doctrine:
            table_prefix: null
            table_suffix: '_log'
            viewer: true
            entities:
                App\Entity\Metadata\Person: ~
            storage_services:
                - '@doctrine.orm.log_entity_manager'
</pre>

When i update my databases, the table 'person_log' appears in the défault database, and it don't use my storage_services configuration (i want to have tables in my log database)
Did i forget something ?

Thanks in advance

Chris

**Comment by DamienHarper** [comment]
@chrisbiaz Thanks for the report, I'll have a look at it asap

**Comment by DamienHarper** [comment]
@chrisbiaz this should be fixed by using `auditor`'s `master` branch

**Comment by DamienHarper** [comment]
@chrisbiaz I close this issue, feel free to reopen it if needed

**Comment by ikleiman** [comment]
Hello!

I'm trying to do this same thing, but storing audits from a second DB in the main DB:

```
dh_auditor:
    enabled: true
    providers:
        doctrine:
            auditing_services:
                - '@doctrine.orm.external_entity_manager'
            storage_services:
                - '@doctrine.orm.default_entity_manager'
            table_prefix: null
            table_suffix: '_audit'
            ignored_columns:
                - 'password'
                - 'created'
                - 'updated'
            entities:
                App\Entity\External\Participant: ~
            viewer: true
```

```
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                profiling_collect_backtrace: '%kernel.debug%'
                use_savepoints: true
            external:
                # configure these for your database server
                url: '%env(DATABASE_URL_EXTERNAL)%'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        default_entity_manager: default
        entity_managers:
            default:
                report_fields_where_declared: true
                validate_xml_mapping: true
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    App:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity/Main'
                        prefix: 'App\Entity\Main'
                        alias: App
            external:
                report_fields_where_declared: true
                validate_xml_mapping: true
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                connection: external
                mappings:
                    External:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity/External'
                        prefix: 'App\Entity\External'
                        alias: External
```

It does not throw any errors, but when I run symfony console make:migration it doesn't recognize the changes.

Thanks in advance!
