### ISSUE TITLE
Incorrect initialization of the "auditing_services" and "storage_services" config parameters 

### ISSUE THREAD

**Issue by Magikan** [DamienHarper/auditor-bundle#257]
| Q                           | A
| ----------------------------| -----------------------
| `auditor-bundle` version    | 4.0.4
| PHP version                 | 7.4.13
| Database                    | MySQL:8.0

#### Summary

Hello, installing the latest bundle. Adding more than 1 EntityManager to the "auditing_services" config and I get Exception "An auditing service named "% s " is already registered.". And another interesting fact is the error will always swear at the last EntityManager. 

The same problem with the "storage_services" parameter.

#### Current behavior

Exception "An auditing service named"% s "is already registered."

#### How to reproduce

Adding more than 1 EntityManager to the "auditing_services" config

#### Expected behavior

Adding more than 1 EntityManager

**Comment by DamienHarper** [comment]
@Magikan thanks for the report. Though, I can't reproduce your issue on my side, could you please post your `dh_auditor.yaml` config file? Also, which version of `auditor` is installed? (I see here that `auditor-bundle` is 4.0.4)

**Comment by Magikan** [comment]
@DamienHarper thanks for quick response. I will assist you as quickly as possible. Thank you!

dh_auditor.yaml  

```

dh_auditor:
  enabled: true
  timezone: '%timezone%'
  providers:
    doctrine:
      table_prefix: 'zuaudit_'
      table_suffix: ''
      ignored_columns:
        - 'createdAt'
        - 'updatedAt'
      
      auditing_services:
        - '@doctrine.orm.default_entity_manager'
        - '@doctrine.orm.common_entity_manager'

```
damienharper/auditor-bundle v4.0.4
damienharper/auditor v1.2.0

my doctrine orm config 
```

    orm:
        auto_generate_proxy_classes: true
        default_entity_manager: default
        entity_managers:
            common:
                connection: common
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    common:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Common/Entity'
                        prefix: 'App\Common\Entity'
                        alias: common
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App

```
