### ISSUE TITLE
Not possible to audit entity without annotations.

### ISSUE THREAD

**Issue by tomme87** [DamienHarper/auditor-bundle#258]
| Q                           | A
| ----------------------------| -----------------------
| `auditor-bundle` version    | 4.1.0
| PHP version                 | 7.4.13
| Database                    | MariaDB 10.4

#### Summary

Adding entities to the config does nothing unless `@Auditable()` annotation is added to the entity.

my config:
```yaml
dh_auditor:
    enabled: true
    providers:
        doctrine:
            table_prefix: null
            table_suffix: '_audit'
            entities:
                App\Entity\User: ~
```

Note: Using annotations everything works as expected.

#### Current behavior

When running `bin/console audit:schema:update --dump-sql `  it says "Nothing to update - your database is already in sync with the current entity metadata. ", but I have added entities to config.
`bin/console doctrine:migrations:diff` also says "No changes detected in your mapping information"

#### How to reproduce

Add entities trough config and not with annotations and run schema update.

#### Expected behavior

A SQL dump with the audit table when running `bin/console audit:schema:update --dump-sql ` or a new migrations when running `bin/console doctrine:migrations:diff`
