### ISSUE TITLE
Doesn't work out of the box?

### ISSUE THREAD

**Issue by dmitryuk** [DamienHarper/auditor-bundle#325]
| Q                           | A
| ----------------------------| -----------------------
| `auditor-bundle` version    | 5.0.3
| PHP version                 | 8.1.0
| Database                    | PostgreSQL

#### Summary

I'm trying to install the package without any configuration,

#### Current behavior

After installed and enabled I receive the error
```
  You have requested a non-existent parameter "dh_auditor.provider.doctrine.configuration".  
```
After some searching I found that I must define providers and entities.
```yaml
dh_auditor:
  enabled: true
  providers:
    doctrine:
      entities:
```
Can we set doctrine as default provider if nothing other is set?

**Comment by DamienHarper** [comment]
@dmitryuk well, it should work out of the box 🤔 
A default config file is created by the flex recipe, it should contain
```yaml
dh_auditor:
    enabled: true
    providers:
        doctrine:
            table_prefix: null
            table_suffix: '_audit'
```

Did you let flex execute recipes (at least `auditor-bundle`'s one) at install time?

**Comment by develth** [comment]
Just also checked that i dont have any entries since August after a Update. It is enabled.

**Comment by DamienHarper** [comment]
@develth thanks for the feedback but I need a bit more info/context: 
- what was the version before update? 
- what's the current version you use now?
- do you declare your entities as auditable using annotations? attributes?

**Comment by develth** [comment]
> what was the version before update?
I Updated in February from 3.4 

> what's the current version you use now?
4.2.0

> do you declare your entities as auditable using annotations? attributes?
Using the packages dh_auditor.yaml via `entites:`

**Comment by develth** [comment]
Think i got the issue.

i modify config in `dev/dh_auditor.yaml` Seems like it overwrites all. If i remove this file, it works and files get listed in viewer.

**Comment by dmitryuk** [comment]
>Did you let flex execute recipes (at least auditor-bundle's one) at install time?
I didn't have Symfony flex installed in the project.

**Comment by develth** [comment]
i have following Config Files:

- `config/dh_auditor.yaml`
- `config/dev/dh_auditor.yaml`
- `config/prod/dh_auditor.yaml`
- `config/test/dh_auditor.yaml`

Main and fulll Setup is in `config/dh_auditor.yaml`. In e.g. `config/prod/dh_auditor.yaml` i disable the viewer with this:

```
dh_auditor:
  providers:
    doctrine:
      viewer: false
```

This disables the auditor.
