### ISSUE TITLE
Duplicated audit entries

### ISSUE THREAD

**Issue by samuel4x4** [DamienHarper/auditor-bundle#330]
| Q                           | A
| ----------------------------| -----------------------
| `auditor-bundle` version    | 5.1.0
| PHP version                 | 8.1.7
| Database                    | MySQL

#### Summary

Entries are duplicated on the audit database tables for all actions: INSERT, UPDATE, ASSOCIATE.

#### Current behavior

Multiple similar entries are added on the entity audit tables for the same object_id, including for INSERT operation, which can't really happen with the same id. I have for example up to 12 similar entries sometimes. 

#### How to reproduce

Any normal operation executed on an audited entity generates duplicated audit entries. 

#### Expected behavior

Audit entries should be added only once on the database.

**Comment by dmitryuk** [comment]
We need more info to reproduce an error.
@samuel4x4 can you provide your `dh_auditor` config?

**Comment by DamienHarper** [comment]
@samuel4x4 I confirm the need to get more information about your current config/setup, I haven't been able to reproduce the issue on my side.

**Comment by DamienHarper** [comment]
@samuel4x4 any chance to get more information about your current config/setup?

**Comment by Navds** [comment]
Samy issue.

- damienharper/auditor-bundle: 5.2.1
- symfony: 5.4.19
- php: 7.4

dh_auditor.yaml:
```yaml
dh_auditor:
    timezone: 'Europe/Paris'
    enabled: true
    providers:
        doctrine:
            table_prefix: null
            table_suffix: '_audit'
            ignored_columns:
                - createdAt
                - updatedAt
                - id
            entities:
                App\Data\Entity\LMS\Course: ~
```


services.yaml:

```yaml
    DH\Auditor\Provider\Doctrine\Auditing\Transaction\TransactionManager:
        arguments: [ '@DH\Auditor\Provider\Doctrine\DoctrineProvider' ]

    DH\Auditor\Provider\Doctrine\Auditing\Event\DoctrineSubscriber:
        arguments: [ '@DH\Auditor\Provider\Doctrine\Auditing\Transaction\TransactionManager' ]
        tags:
            - { name: doctrine.event_subscriber }
```
