### ISSUE TITLE
Symfony 7 compatibility

### ISSUE THREAD

**Issue by b1rdex** [DamienHarper/auditor-bundle#382]
`\DH\AuditorBundle\Routing\RoutingAnnotationLoader` is unusable @ Symfony 7

```
Cannot autowire service "DH\AuditorBundle\Routing\RoutingAnnotationLoader":
argument "$annotatedRouteController" of method "__construct()"
references class "Symfony\Bundle\FrameworkBundle\Routing\AnnotatedRouteControllerLoader"
but no such service exists.
```

Temporal workaround:

1. add to `services.yaml` (to `services` section):
```
    DH\AuditorBundle\Controller\ViewerController:
        tags: ['controller.service_arguments']
```
2. replace `config/routes/dh_auditor.yaml` contents with the following:
```
dh_auditor_list_audits:
    path: /admin/audit
    controller: DH\AuditorBundle\Controller\ViewerController::listAuditsAction
    
dh_auditor_show_transaction:
    path: /admin/audit/transaction/{hash}
    controller: DH\AuditorBundle\Controller\ViewerController::showTransactionAction

dh_auditor_show_entity_history:
    path: /admin/audit/{entity}/{id?}
    controller: DH\AuditorBundle\Controller\ViewerController::showEntityHistoryAction
```
(adjust `/admin` prefix for your needs)
